'use client'

import { useState } from 'react'

export default function FAQ() {
  const [openFAQ, setOpenFAQ] = useState<number | null>(0) // First FAQ open by default

  const faqs = [
    {
      question: "What is a Character Headcanon Generator and how does it work?",
      answer: "A Character Headcanon Generator is an AI-powered tool that creates detailed backstories, traits, and scenarios for fictional characters. It works by using advanced algorithms to analyze user input (such as character name, basic traits, or story setting) and generate unique, creative headcanons. This tool is particularly useful for writers, roleplayers, and fanfiction enthusiasts looking to expand their character development process."
    },
    {
      question: "What types of headcanons can I create with a Character Headcanon Generator?",
      answer: "You can create various types of headcanons including personality traits, background stories, relationships with other characters, skills and abilities, fears and motivations, family history, and character quirks. The generator offers multiple categories to choose from, allowing you to customize the type of content that best fits your creative needs."
    },
    {
      question: "How can I use a Character Headcanon Generator for my writing or roleplaying?",
      answer: "The generator is perfect for overcoming writer's block, developing complex characters, creating backstories for tabletop RPG characters, expanding fanfiction characters, and adding depth to original characters. You can use the generated content as inspiration, starting points, or direct additions to your creative projects."
    },
    {
      question: "Are the headcanons generated by AI unique and copyright-free?",
      answer: "Yes, all headcanons generated by our AI are unique and original content created specifically for your input. The AI doesn't copy existing copyrighted material but instead creates new, original ideas based on the parameters you provide. You're free to use, modify, and incorporate the generated headcanons into your creative works."
    },
    {
      question: "Can I edit or expand on the headcanons generated by the AI?",
      answer: "Absolutely! The generated headcanons are meant to serve as inspiration and starting points for your creativity. You can freely edit, expand, combine, or modify any generated content to better fit your vision. The AI-generated content is designed to spark your imagination and provide a foundation for further development."
    },
    {
      question: "Is a Character Headcanon Generator suitable for developing characters in different genres?",
      answer: "Yes, our generator is versatile and works across all genres including fantasy, science fiction, romance, mystery, horror, contemporary fiction, and more. You can specify genre preferences and writing styles to ensure the generated headcanons match the tone and setting of your particular creative project."
    },
    {
      question: "How does a Character Headcanon Generator compare to traditional character development methods?",
      answer: "While traditional character development methods rely on structured questionnaires and manual brainstorming, our AI generator provides instant, creative inspiration that can spark new ideas you might not have considered. It's designed to complement traditional methods by offering fresh perspectives and overcoming creative blocks when you need them most."
    }
  ]

  const toggleFAQ = (index: number) => {
    setOpenFAQ(openFAQ === index ? null : index)
  }

  return (
    <section className="py-20 px-6 bg-white dark:bg-dark-bg transition-colors">
      <div className="max-w-4xl mx-auto">
        {/* Section Header */}
        <div className="text-center mb-16">
          <h2 className="inline-block bg-material-green-600 text-white px-8 py-3 rounded-lg text-2xl font-bold mb-4">
            FAQ
          </h2>
          <p className="text-gray-600 dark:text-gray-400 text-lg">
            Here are some of the most frequently asked questions.
          </p>
        </div>

        {/* FAQ Items */}
        <div className="space-y-4">
          {faqs.map((faq, index) => (
            <div 
              key={index}
              className="bg-light-card dark:bg-dark-card rounded-xl border border-light-border dark:border-dark-border overflow-hidden transition-colors"
            >
              <button
                onClick={() => toggleFAQ(index)}
                className="w-full p-6 text-left flex items-center justify-between hover:bg-gray-100 dark:hover:bg-dark-bg transition-colors duration-200"
              >
                <h3 className="text-gray-900 dark:text-white font-medium text-lg pr-4">
                  {faq.question}
                </h3>
                <div className="flex-shrink-0">
                  <svg 
                    className={`w-6 h-6 text-gray-400 transform transition-transform duration-200 ${
                      openFAQ === index ? 'rotate-45' : ''
                    }`}
                    fill="none" 
                    stroke="currentColor" 
                    viewBox="0 0 24 24"
                  >
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 6v6m0 0v6m0-6h6m-6 0H6" />
                  </svg>
                </div>
              </button>
              
              {openFAQ === index && (
                <div className="px-6 pb-6">
                  <div className="border-t border-light-border dark:border-dark-border pt-4">
                    <p className="text-gray-600 dark:text-gray-400 leading-relaxed">
                      {faq.answer}
                    </p>
                  </div>
                </div>
              )}
            </div>
          ))}
        </div>
      </div>
    </section>
  )
}